const jsonAddr = 'https://atibayan.github.io/wanderfulWorld/data.json'
// const jsonAddr = './data.json'  // for local testing
const dataPromise = fetch(jsonAddr).then(results => results.json()).then(
  (data) => {return data;}
); // retrieves the json data from file and returns a Promise instance

const emojis = {
  'superb!':0x1F601,
  'loveit!':0x1F60D,
  'pricey!':0x1F911,
  'it rocks!':0x1F918,
  'meh!':0x1F615,
  'dontgo!':0x1F621
};

const colors = {
  colorLight: '#C5C6C7',
  colorLightAccent: '#66FCF1',
  colorMediumAccent: '#45A29E',
  colorDarkAccent: '#1F2833',
  colorDark: '#0B0C10'
}

const countryList = [
	"Canada",
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo (the Democratic Republic of the)",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands [Malvinas]",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Boliconstian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands"
];

const dummyComments = [
  {
    fname: "John Doe",
    country: "Istanbul",
    rate: "superb!",
    story: 'I will definitely visit Istanbul again. Hagia Sophia is a gem! Basilica Cistern did not disappoint. I love Simit!'
  },
  {
    fname: "Adrian Clayton",
    country: "Philippines",
    rate: "it rocks!",
    story: 'Philippines is a gem! I have tried Lechon in Cebu. Mingled with Tarsiers in Bohol. It is a great experience!'
  },
  {
    fname: "Connor Tanner",
    country: "Austria",
    rate: "meh!",
    story: 'Stores in Austria is not convenient, especially for travelers outside of Europe. They are closing early. I was craving for soda and all the stores are closed around our hotel. Nevertheless, it was a good trip, specifically the Austrian Alps.'
  },
  {
    fname: "Herman Miller",
    country: "France",
    rate: "pricey!",
    story: 'I have stayed in France for a few weeks, all I can say is that it is really one of the expensive destinations that I went to. You need to pay to use public washrooms. '
  },
  {
    fname: "Carol Sanders",
    country: "Italy",
    rate: "dontgo!",
    story: 'My rental car was broken into Tuscany. To make the matter worst, the rental company has no insurance covering for this kind of scenario. It was an unpleasant trip. '
  },
  {
    fname: "Anton Kirkland",
    country: "Vietnam",
    rate: "it rocks!",
    story: 'I have spent a few weeks in Ho Chi Minh, stayed in an AirBnB accomodation. It was good experience to eat local food such as Pho and Banh Mi. We were able to do some thrift shopping in Ben Thanh. I was able to buy some things with a good deal. '
  },
  {
    fname: "Taylor Brand",
    country: "Spain",
    rate: "loveit!",
    story: 'I have been able to see the Sagrada Familia. It felt surreal. Been able to tour around Barcelona for a few days. Then, we went to Valencia in one of their wieries and was able to try excellent wines. '
  }
];

const MAX_COMMENT = 11;

const gridAreas2Col = [
  '1 / 1 / 2 / 2',
  '1 / 2 / 2 / 3',
  '2 / 1 / 3 / 3',
  '3 / 1 / 4 / 2',
  '3 / 2 / 4 / 3',
  '4 / 1 / 5 / 3',
  '5 / 1 / 6 / 2',
  '5 / 2 / 6 / 3',
  '6 / 1 / 7 / 2',
  '6 / 2 / 7 / 3',
  '7 / 1 / 8 / 3',
  '8 / 1 / 9 / 2',
  '8 / 2 / 9 / 3',
  '9 / 1 / 10 / 3',
  '10 / 1 / 11 / 2',
  '10 / 2 / 11 / 3',
  '11 / 1 / 12 / 3'
];

const gridAreas3Col = [
  '1 / 1 / 2 / 2',
  '1 / 2 / 2 / 3',
  '1 / 3 / 3 / 4',
  '2 / 1 / 3 / 3',
  '3 / 1 / 4 / 2',
  '3 / 2 / 4 / 4',
  '4 / 1 / 5 / 3',
  '4 / 3 / 6 / 4',
  '5 / 1 / 6 / 2',
  '5 / 2 / 6 / 3',
  '6 / 1 / 7 / 2',
  '6 / 2 / 7 / 4'
];


